# Generated by Django 4.2.1 on 2023-06-03 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_nombre', models.CharField(max_length=100, verbose_name='Nombre del doctor')),
                ('doctor_direccion', models.CharField(max_length=200, verbose_name='Direcicon de la casa del doctor')),
                ('doctor_telefono', models.CharField(max_length=12, verbose_name='Telefono del doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('especialidad_id', models.AutoField(primary_key=True, serialize=False)),
                ('especialidad_nombre', models.CharField(max_length=100, verbose_name='Nombre de la  especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Tipodocumento',
            fields=[
                ('tipo_documento_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento_nombre', models.CharField(max_length=100, verbose_name='Nombre del tipo seguro')),
            ],
        ),
        migrations.CreateModel(
            name='Tiposeguro',
            fields=[
                ('tipo_seguro_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_seguro_nombre', models.CharField(max_length=100, verbose_name='Nombre del tipo seguro')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('paciente_id', models.AutoField(primary_key=True, serialize=False)),
                ('nro_documento', models.CharField(max_length=12, verbose_name='Numero de documento de identidad')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombre del paciente')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos del paciente')),
                ('direccion', models.CharField(max_length=200, verbose_name='Direccion del paciente')),
                ('fecha_nacimiento', models.DateTimeField()),
                ('tipo_documento_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.tipodocumento')),
                ('tipo_seguro_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.tiposeguro')),
            ],
        ),
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('cita_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_cita', models.DateTimeField()),
                ('observaciones', models.CharField(max_length=200, verbose_name='Observaciones')),
                ('doctor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.doctor')),
                ('especialidad_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.especialidad')),
                ('paciente_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.paciente')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
