# Generated by Django 4.2.1 on 2023-06-03 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_rename_doctor_id_citas_doctor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='tipo_documento_id',
            new_name='tipo_documento',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='tipo_seguro_id',
            new_name='tipo_seguro',
        ),
    ]
