# Generated by Django 4.2.1 on 2023-06-03 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_paciente_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='paciente',
            table='pacientes',
        ),
    ]
