# Generated by Django 4.2.1 on 2023-06-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_paciente_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_direccion',
            field=models.CharField(max_length=200, verbose_name='Direccion de la casa del doctor'),
        ),
    ]
